# Todos los nombres coinciden exactamente con src/endocenter/config.py

# =============================================================================
# APPLICATION CONFIG
# =============================================================================
app_name: "EndoCenter MLOps"
app_version: "1.0.0"
environment: "development"
debug: true

# =============================================================================
# API CONFIG
# =============================================================================
api_host: "0.0.0.0"
api_port: 8000
api_prefix: "/api/v1"

# =============================================================================
# GPU CONFIG - RTX 5070 Optimized
# =============================================================================
gpu_enabled: true
cuda_device: "cuda:0"
gpu_memory_limit: 11000  # MB
gpu_optimization_level: "high"

# =============================================================================
# MODEL CONFIG - GPU Optimized
# =============================================================================
embedding_model: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
embedding_device: "cuda"
embedding_batch_size: 128  # Large batch for RTX 5070
embedding_precision: "fp16"  # Mixed precision for performance
top_k_results: 10
max_chunk_size: 500
chunk_overlap: 100
similarity_threshold: 0.3

# =============================================================================
# FAISS CONFIG - GPU Optimized
# =============================================================================
faiss_gpu_enabled: true
faiss_gpu_memory_limit: 8000  # MB for FAISS
faiss_index_type: "IndexFlatL2"
faiss_training_batch_size: 10000

# =============================================================================
# LLM CONFIG
# =============================================================================
llm_api_url: "http://localhost:11434/api/generate"
llm_model: "llama3"
llm_timeout: 30
llm_max_retries: 3

# =============================================================================
# DATA PATHS
# =============================================================================
# Nota: Estos se crearán como Path objects automáticamente por los validators
data_dir: "./data"
embeddings_dir: "./data/embeddings"
chunks_dir: "./data/chunks"
preprocessed_dir: "./data/preprocessed"
raw_dir: "./data/raw"

# =============================================================================
# DATABASE CONFIG - PostgreSQL
# =============================================================================
db_host: "localhost"
db_port: 5433  # Cambiado a 5433 para coincidir con tu Docker
db_name: "endocenter"
db_user: "endocenter_user"  # Corregido para coincidir con Docker
db_password: "endocenter_pass"  # Corregido para coincidir con Docker
# database_url se construye automáticamente o se toma del Field default

# =============================================================================
# MONITORING CONFIG
# =============================================================================
log_level: "INFO"
log_format: "detailed"
metrics_enabled: true
gpu_monitoring: true
performance_logging: true